spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keyGenerator
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  error:
    include-message: always
  port: 8081
